# Generated by Django 4.0.6 on 2022-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_images1_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images1',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
